//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangluongnhanvien
    {
        public Nullable<int> thang { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<int> Ngaycong { get; set; }
        public string noidung { get; set; }
        public Nullable<decimal> tienphucap { get; set; }
        public Nullable<decimal> tienthuong { get; set; }
        public Nullable<decimal> tienluongcoban { get; set; }
        public Nullable<decimal> bhxh { get; set; }
        public Nullable<decimal> bhyt { get; set; }
        public Nullable<decimal> bhtn { get; set; }
        public Nullable<decimal> tientamung { get; set; }
        public Nullable<decimal> tienluong { get; set; }
        public Nullable<decimal> tienbhxh { get; set; }
        public Nullable<decimal> tientruocthue { get; set; }
        public Nullable<decimal> tienthue { get; set; }
        public Nullable<decimal> tongbaohiem { get; set; }
        public Nullable<decimal> tienthuclinh { get; set; }
        public Nullable<decimal> giamtruphuthuoc { get; set; }
        public Nullable<decimal> giamtrucanhan { get; set; }
        public Nullable<decimal> tonggiamtru { get; set; }
        public Nullable<decimal> tienbhyt { get; set; }
        public Nullable<decimal> tienbhtn { get; set; }
        public int id { get; set; }
        public int machitietbcc { get; set; }
        public string mabcc { get; set; }
        public Nullable<decimal> congdoan { get; set; }
        public Nullable<decimal> tiencongdoan { get; set; }
        public Nullable<decimal> tienbhxhctytra { get; set; }
        public Nullable<decimal> tienbhytctytra { get; set; }
        public Nullable<decimal> tienbtntnctytra { get; set; }
        public Nullable<decimal> tiencongdoanctytra { get; set; }
        public Nullable<decimal> luongngoaigio { get; set; }
        public Nullable<decimal> phucapantrue { get; set; }
        public Nullable<decimal> phucapkhac { get; set; }
    
        public virtual bangcc bangcc { get; set; }
    }
}
