//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bangcc()
        {
            this.chitietbangccs = new HashSet<chitietbangcc>();
            this.bangluongnhanviens = new HashSet<bangluongnhanvien>();
        }
    
        public string so { get; set; }
        public Nullable<int> thang { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<int> ngaycong { get; set; }
        public string mabp { get; set; }
        public string noidung { get; set; }
    
        public virtual dmbp dmbp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietbangcc> chitietbangccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bangluongnhanvien> bangluongnhanviens { get; set; }
    }
}
