//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsocai
    {
        public string so { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string lydo { get; set; }
        public string tkdu { get; set; }
        public Nullable<double> tienno { get; set; }
        public Nullable<double> tienco { get; set; }
    
        public virtual vsocai vsocai { get; set; }
    }
}
