//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietbangcc
    {
        public string so { get; set; }
        public string manv { get; set; }
        public Nullable<double> ngaycong { get; set; }
        public Nullable<double> ngayphep { get; set; }
        public Nullable<double> ngaykhongphep { get; set; }
        public Nullable<double> tienphucap { get; set; }
        public Nullable<double> tienthuong { get; set; }
        public int id { get; set; }
        public Nullable<decimal> tienphat { get; set; }
    
        public virtual bangcc bangcc { get; set; }
        public virtual dmnv dmnv { get; set; }
    }
}
