//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietphieuketoan
    {
        public int id { get; set; }
        public string so { get; set; }
        public string tkno { get; set; }
        public string tkco { get; set; }
        public string noidung { get; set; }
        public Nullable<double> tien { get; set; }
    
        public virtual phieuketoan phieuketoan { get; set; }
    }
}
