//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmnh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmnh()
        {
            this.giaybaonoes = new HashSet<giaybaono>();
        }
    
        public string so { get; set; }
        public string stk { get; set; }
        public string tennh { get; set; }
        public string chinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giaybaono> giaybaonoes { get; set; }
    }
}
