//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmtk
    {
        public string matk { get; set; }
        public string tentk { get; set; }
        public string tkme { get; set; }
        public Nullable<int> captk { get; set; }
    }
}
