//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class giaybaono
    {
        public string so { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string manv { get; set; }
        public string noidung { get; set; }
        public string ctlq { get; set; }
        public string manh { get; set; }
        public Nullable<decimal> tien { get; set; }
        public string tkco { get; set; }
        public string tkno { get; set; }
    
        public virtual dmnh dmnh { get; set; }
        public virtual dmnv dmnv { get; set; }
        public virtual dmtk dmtk { get; set; }
        public virtual dmtk dmtk1 { get; set; }
    }
}
