//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ketoantienluongEntities : DbContext
    {
        public ketoantienluongEntities()
            : base("name=ketoantienluongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bangcc> bangccs { get; set; }
        public virtual DbSet<dmbp> dmbps { get; set; }
        public virtual DbSet<dmcv> dmcvs { get; set; }
        public virtual DbSet<nguoidung> nguoidungs { get; set; }
        public virtual DbSet<thamsoluong> thamsoluongs { get; set; }
        public virtual DbSet<thamsothuetncn> thamsothuetncns { get; set; }
        public virtual DbSet<bacluong> bacluongs { get; set; }
        public virtual DbSet<dmnv> dmnvs { get; set; }
    }
}
