//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuketoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuketoan()
        {
            this.chitietphieuketoans = new HashSet<chitietphieuketoan>();
        }
    
        public string so { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string manv { get; set; }
        public string noidung { get; set; }
        public string ctlq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietphieuketoan> chitietphieuketoans { get; set; }
        public virtual dmnv dmnv { get; set; }
    }
}
