//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class socai
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string sophieu { get; set; }
        public string diengiai { get; set; }
        public string nhatkychung { get; set; }
        public string tkdu { get; set; }
        public Nullable<decimal> sotienno { get; set; }
        public Nullable<decimal> sotienco { get; set; }
    }
}
