//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class thamsothuetncn
    {
        public string mucthue { get; set; }
        public Nullable<double> tientu { get; set; }
        public Nullable<double> tienden { get; set; }
        public Nullable<double> tyle { get; set; }
        public Nullable<int> muc { get; set; }
    }
}
