//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeToanTienLuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class thamsoluong
    {
        public string mats { get; set; }
        public string tents { get; set; }
        public string noidung { get; set; }
        public Nullable<double> tyle { get; set; }
    }
}
